### ISSUE TITLE
Link to repo from npm

### ISSUE THREAD

**Issue by IanVS** [rafaelrozon/eslint-plugin-storybook#1]
Hi, I had a bit of a tough time finding this repo, since it is not linked from https://www.npmjs.com/package/eslint-plugin-storybook.  So this is just a friendly suggestion to add the proper fields to the `package.json`.

**Comment by rafaelrozon** [comment]
Thanks, @IanVS. I'll update the package.json file.

**Comment by rafaelrozon** [comment]
Closing this. Configuration is updated.
