### ISSUE TITLE
Rule suggestion: use-controls

### ISSUE THREAD

**Issue by IanVS** [rafaelrozon/eslint-plugin-storybook#2]
Hi, I was wondering if you've considered adding a rule to enforce the use of addon-controls.  For my own use case, I'd love to enforce that the first CSF story in a file contains an `args`  parameter (or even just any parameter, since it could be named anything or destructured immediately).  Would you consider adding such a rule?

**Comment by rafaelrozon** [comment]
hey @IanVS, thanks for the suggestions. I think that having the rule to enforce the use of addon-controls could be good. There are different ways that I think this could be achieved:

1. check if the knob add-ons is being used in the file
2. check that there's a default export on the page and it has a component field
3. check if the exported components have an args field

It could be a combination of these 3. Maybe all of them, maybe just some. 

About ensuring that the first CSF story in a file contains an args parameter, it seems to me that people could be arranging their stories in different ways and I'm not sure if it's a practice that will cover most of the use cases. Maybe a rule that specifies at least one story to be named in a certain way and then check if that one has an args parameter?

**Comment by IanVS** [comment]
Hi, thanks for the response.  My thinking on enforcing the first story to have controls is that it works out really nicely in the `docs` view, such that there is a props table already usually, and the controls are just added into that one.  I understand that maybe not everyone would want that, but then of course they can just not enable the rule.  I'll probably write such a rule on my own, and I can then discuss more concretely how well it works or not for my team.  :)

**Comment by rafaelrozon** [comment]
@IanVS, feel free to submit a PR or let me know if you need help with anything.
